name: Functions Deploy

on:
  push:
    branches: 
      - master
    paths:
      - 'functions/**'

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Dependencies
        run: npm ci
        working-directory: functions

      - name: Lint Functions
        run: npm run lint
        working-directory: functions

      - name: Deploy To Firebase
        uses: w9jds/firebase-action@v1.3.1
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
