name: Website Deploy

on:
  push:
    branches: 
      - master
    paths:
      - 'website/**'
      - 'firebase.json'

jobs:
  deploy_hugo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.73.0'
          extended: true

      - name: Install Dependencies
        run: npm ci
        working-directory: website

      - name: Build Website
        run: npm run build
        working-directory: website

      - name: Deploy To Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
